### ISSUE TITLE
是否考虑加入ElvUI_WindTools里面的功能？

### ISSUE THREAD

**Issue by swetlover** [fang2hou/WindDungeonHelper#4]
ElvUI_WindTools很好很强大，非常希望使用里面的相关功能，但是原始界面风格强迫症无法适应ElvUI，所以是否可以将ElvUI_WindTools中除美化外观以外的功能加入到WindDungeonHelper中呢？
非常感谢！

**Comment by fang2hou** [comment]
很多功能是基于elvui内置函数的基础上做的开发, 移不出来的, 而且最重要的是, 这工作量非常大, 我自己不用的前提下肯定是不会这样去做的.

**Comment by swetlover** [comment]
明白，非常感谢！
