### ISSUE TITLE
可以增加一个小功能吗？

### ISSUE THREAD

**Issue by qxinfup** [fang2hou/WindDungeonHelper#5]
1、进入地下城后或离开地下城后，自动在指定频道里发送消息。
2、用途：玩台服，每次离开副本时或进入副本时，都会主动主动问候下队友。之前一直用Dungeon Helper这个插件可实现这种功能，但是目前这个插件更新后也没法用。
3、谢谢！

**Comment by qxinfup** [comment]
Dungeon Helper插件地址，第三张图片的那个功能就是。
https://www.curseforge.com/wow/addons/broker_findgroup/screenshots

**Comment by fang2hou** [comment]
我也是玩的台服, 该功能在我另外一款插件中是有的, 包括钥石通报等.
https://github.com/fang2hou/ElvUI_WindTools

**Comment by qxinfup** [comment]
> 我也是玩的台服, 该功能在我另外一款插件中是有的, 包括钥石通报等.
> https://github.com/fang2hou/ElvUI_WindTools

非常感谢，这个插件功能很多很实用，我去试试。
