### ISSUE TITLE
Numerical System not working properly.

### ISSUE THREAD

**Issue by KurtzPT** [fang2hou/WindDungeonHelper#6]
All messages and scoreboard in the end show up like this:

![image](https://user-images.githubusercontent.com/14930057/166305775-85ffb7f8-3300-4170-aa89-96453630dd0b.png)

In customization example:

![image](https://user-images.githubusercontent.com/14930057/166306003-fbd289af-5866-40b2-abfe-2aebd1323df3.png)

**Comment by fang2hou** [comment]
fixed in 1.7.2
